backend/core/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('index/', views.DashboardIndexView.as_view(), name='dashboard_index'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('tournaments/', views.TournamentListView.as_view(), name='tournaments'),
    path('tournaments/add-new/', views.AddNewTournament.as_view(), name='add_new_tournament'),
    path('tournaments/<int:pk>/', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('tournaments/delete/<int:pk>/', views.TournamentDeleteView.as_view(), name='tournament_delete'),
    path('teams/', views.TeamListView.as_view(), name='teams'),
    path('teams/add-new/', views.AddNewTeamName.as_view(), name='add_new_team'),
    path('teams/<int:pk>/', views.TeamNameUpdateView.as_view(), name='team_update'),
    path('teams/delete/<int:pk>/', views.TeamNameDeleteView.as_view(), name='team_delete'),
    path('venues/', views.VenueListView.as_view(), name='venues'),
    path('venues/add-new/', views.AddNewVenue.as_view(), name='add_new_venue'),
    path('venues/<int:pk>/', views.VenueNameUpdateView.as_view(), name='venue_update'),
    path('venues/delete/<int:pk>/', views.VenueNameDeleteView.as_view(), name='venue_delete'),
    path('faqs/', views.FAQListView.as_view(), name='faq_list'),
    path('faqs/add-new/', views.AddNewFAQ.as_view(), name='add_new_faq'),
    path('faqs/<int:pk>/', views.FAQUpdateView.as_view(), name='faq_update'),
    path('faqs/delete/<int:pk>/', views.FAQDeleteView.as_view(), name='faq_delete'),
]

backend/faq/urls.py
from django.urls import path
from faq import views

app_name = 'faq'
urlpatterns = [
    path('', views.FAQView.as_view(), name='faq'),
]

backend/dashboard/views.py
from django.shortcuts import render

# Create your views here.

backend/templates/dashboard/add_form.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>


        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="container">

                <div class="container">
                    {% if messages %}
					{% for msg in messages %}

						<div class="alert alert-warning alert-dismissible fade show" role="alert">
						  <strong>Hey!</strong> {{ msg }}.
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>

					{% endfor %}
					{% endif %}
                    <div class="row layout-top-spacing">
                        <div id="basic" class="col-lg-12 layout-spacing">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-header">
                                    <div class="row">
                                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                            <h4>Form</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="widget-content widget-content-area">

                                    <div class="row">
                                        <div class="col-lg-12 col-12 mx-auto">
                                            <form method="post" enctype="multipart/form-data">
                                                <div class="form-group">
                                                    {% csrf_token %}
                                                    {{ form | crispy }}

                                                    <input type="submit" name="txt" class="mt-4 btn btn-primary">
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>


                    </div>

                </div>
            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>

    {% endblock body %}

backend/templates/dashboard/faq_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>


        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">

                {% if messages %}
					{% for msg in messages %}

						<div class="alert alert-warning alert-dismissible fade show" role="alert">
						  <strong>Hey!</strong> {{ msg }}.
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>

					{% endfor %}
                {% endif %}

                <div class="row layout-spacing">
                    <div class="col-lg-12">

                        <div class="layout-spacing">
                            <br>
                            <a class="btn btn-primary" href="{% url 'dashboard:add_new_faq' %}">Add FAQ</a>
                        </div>

                        <div class="statbox widget box box-shadow">
                            <div class="widget-content widget-content-area">
                                <table id="style-3" class="table style-3  table-hover">
                                    <thead>
                                        <tr>
                                            <th class="checkbox-column"> Record Id </th>
                                            <th>Question</th>
                                            <th>Answer</th>
                                            <th class="text-center dt-no-sorting">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for faq in faqs %}

                                        <tr>
                                            <td class="checkbox-column"> {{faq.id}} </td>
                                            <td><div><p>{{faq.question}}</p></div></td>
                                            <td><div><p>{{faq.answer}}</p></div></td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    <li><a href="{% url 'dashboard:faq_update' faq.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                                    <li><a href="{% url 'dashboard:faq_delete' faq.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash p-1 br-6 mb-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></a></li>
                                                </ul>
                                            </td>
                                            </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>


{% endblock body %}



backend/templates/dashboard/sidebar.html
<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="sidebar">

        <ul class="navbar-nav theme-brand flex-row  text-center">
            <li class="nav-item theme-logo">
                <a href="">
<!--                    {% if request.user.is_authenticated %}-->
<!--                        <img src="{{ request.user.profile.image.url }}" class="navbar-logo" alt="logo">-->
<!--                    {% else %}-->
<!--                        -->
<!--                    {% endif %}-->
                </a>
            </li>
            <li class="nav-item theme-text">
                <a href="{% url 'dashboard:dashboard_index' %}" class="nav-link"> T-20 Predictor </a>
            </li>
        </ul>

        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu active">
                <a href="{% url 'dashboard:dashboard_index' %}" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        <span>Dashboard</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu recent-submenu mini-recent-submenu list-unstyled show" id="dashboard" data-parent="#accordionExample">
                    <li class="active">
                        <a href="{% url 'dashboard:user_list' %}"> User List </a>
                    </li>

                </ul>
            </li>

            <li class="menu menu-heading">
                <div class="heading"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg><span>Features</span></div>
            </li>

            <li class="menu">
                <a href="{% url 'dashboard:tournaments' %}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-box"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>
                        <span>Tournament List</span>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="{% url 'dashboard:teams' %}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                        <span>Team List</span>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="{% url 'dashboard:venues' %}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                        <span>Venue List</span>
                    </div>
                </a>
            </li>


            <li class="menu menu-heading">
                <div class="heading"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg><span>Management</span></div>
            </li>

            <li class="menu">
                <a href="{% url 'dashboard:faq_list' %}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                        <span>FAQ List</span>
                    </div>
                </a>
            </li>

            <li class="menu">
                <a href="" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                        <span>About Us</span>
                    </div>
                </a>
            </li>


            <li class="menu">
                <a href="" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-target"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg>
                        <span>Contact Us</span>
                    </div>
                </a>
            </li>



        </ul>

    </nav>

</div>
<!--  END SIDEBAR  -->

backend/templates/dashboard/team_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>


        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">

                {% if messages %}
					{% for msg in messages %}

						<div class="alert alert-warning alert-dismissible fade show" role="alert">
						  <strong>Hey!</strong> {{ msg }}.
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>

					{% endfor %}
                {% endif %}

                <div class="row layout-spacing">
                    <div class="col-lg-12">

                        <div class="layout-spacing">
                            <br>
                            <a class="btn btn-primary" href="{% url 'dashboard:add_new_team' %}">Add New Team</a>
                        </div>

                        <div class="statbox widget box box-shadow">
                            <div class="widget-content widget-content-area">
                                <table id="style-3" class="table style-3  table-hover">
                                    <thead>
                                        <tr>
                                            <th class="checkbox-column"> Record Id </th>
                                            <th>Team Name</th>
                                            <th>Belongs To</th>
                                            <th class="text-center dt-no-sorting">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for team in teams %}

                                        <tr>
                                            <td class="checkbox-column"> {{team.id}} </td>
                                            <td>{{team.team}}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <p> {{team.tournament.name}} </p>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    <li><a href="{% url 'dashboard:team_update' team.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                                    <li><a href="{% url 'dashboard:team_delete' team.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash p-1 br-6 mb-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></a></li>
                                                </ul>
                                            </td>
                                            </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>


{% endblock body %}



backend/templates/dashboard/tournament_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>


        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">

                {% if messages %}
					{% for msg in messages %}

						<div class="alert alert-warning alert-dismissible fade show" role="alert">
						  <strong>Hey!</strong> {{ msg }}.
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>

					{% endfor %}
                {% endif %}

                <div class="row layout-spacing">
                    <div class="col-lg-12">

                        <div class="layout-spacing">
                            <br>
                            <a class="btn btn-primary" href="{% url 'dashboard:add_new_tournament' %}">Add New Tournament</a>
                        </div>

                        <div class="statbox widget box box-shadow">
                            <div class="widget-content widget-content-area">
                                <table id="style-3" class="table style-3  table-hover">
                                    <thead>
                                        <tr>
                                            <th class="checkbox-column"> Record Id </th>
                                            <th>Tournament Name</th>
<!--                                            <th>Status</th>-->
                                            <th>About</th>
                                            <th class="text-center dt-no-sorting">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for tournament in tournaments %}

                                        <tr>
                                            <td class="checkbox-column"> {{tournament.id}} </td>
                                            <td>
                                                {{tournament.name}}
                                            </td>
<!--                                            {% if product.status is True %}-->
<!--                                                <td><span class="badge badge-success inv-status">Open</span></td>-->
<!--                                            {% else %}-->
<!--                                                <td><span class="badge badge-danger inv-status">Close</span></td>-->
<!--                                            {% endif %}-->
                                            <td>
                                                <div class="d-flex">
                                                    <p> {{tournament.description}} </p>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    <li><a href="{% url 'dashboard:tournament_update' tournament.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                                    <li><a href="{% url 'dashboard:tournament_delete' tournament.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash p-1 br-6 mb-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></a></li>
                                                </ul>
                                            </td>
                                            </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>


{% endblock body %}



backend/templates/dashboard/venue_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container sidebar-closed sbar-open" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>


        {% include 'dashboard/sidebar.html' %}

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">

                {% if messages %}
					{% for msg in messages %}

						<div class="alert alert-warning alert-dismissible fade show" role="alert">
						  <strong>Hey!</strong> {{ msg }}.
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>

					{% endfor %}
                {% endif %}

                <div class="row layout-spacing">
                    <div class="col-lg-12">

                        <div class="layout-spacing">
                            <br>
                            <a class="btn btn-primary" href="{% url 'dashboard:add_new_venue' %}">Add New Venue</a>
                        </div>

                        <div class="statbox widget box box-shadow">
                            <div class="widget-content widget-content-area">
                                <table id="style-3" class="table style-3  table-hover">
                                    <thead>
                                        <tr>
                                            <th class="checkbox-column"> Record Id </th>
                                            <th>Venue Name</th>
                                            <th>Belongs To</th>
                                            <th class="text-center dt-no-sorting">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for venue in venues %}

                                        <tr>
                                            <td class="checkbox-column"> {{venue.id}} </td>
                                            <td>{{venue.city}}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <p> {{venue.tournament.name}} </p>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    <li><a href="{% url 'dashboard:venue_update' venue.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                                    <li><a href="{% url 'dashboard:venue_delete' venue.pk %}" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash p-1 br-6 mb-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></a></li>
                                                </ul>
                                            </td>
                                            </tr>

                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!--  END CONTENT AREA  -->
    </div>


{% endblock body %}

