backend/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.Userlogin, name='login'),
    path('forgot-password/', views.ForgotPassword, name='forgot-password'),
    path('change-password/<token>/', views.ChangePassword, name='change-password'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile-form/', views.ProfileForm.as_view(), name='profile-form'),
    path('logout/', views.LogoutPage, name='logout'),
]

backend/contactus/urls.py
from django.urls import path
from contactus import views

app_name = 'contactus'
urlpatterns = [
    path('', views.ContactUsView.as_view(), name='contactus_form'),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('index/', views.DashboardIndexView.as_view(), name='dashboard_index'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('tournaments/', views.TournamentListView.as_view(), name='tournaments'),
    path('tournaments/add-new/', views.AddNewTournament.as_view(), name='add_new_tournament'),
    path('tournaments/<int:pk>/', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('tournaments/delete/<int:pk>/', views.TournamentDeleteView.as_view(), name='tournament_delete'),
    path('teams/', views.TeamListView.as_view(), name='teams'),
    path('teams/add-new/', views.AddNewTeamName.as_view(), name='add_new_team'),
    path('teams/<int:pk>/', views.TeamNameUpdateView.as_view(), name='team_update'),
    path('teams/delete/<int:pk>/', views.TeamNameDeleteView.as_view(), name='team_delete'),
    path('venues/', views.VenueListView.as_view(), name='venues'),
    path('venues/add-new/', views.AddNewVenue.as_view(), name='add_new_venue'),
    path('venues/<int:pk>/', views.VenueNameUpdateView.as_view(), name='venue_update'),
    path('venues/delete/<int:pk>/', views.VenueNameDeleteView.as_view(), name='venue_delete'),
    path('faqs/', views.FAQListView.as_view(), name='faq_list'),
    path('faqs/add-new/', views.AddNewFAQ.as_view(), name='add_new_faq'),
    path('faqs/<int:pk>/', views.FAQUpdateView.as_view(), name='faq_update'),
    path('faqs/delete/<int:pk>/', views.FAQDeleteView.as_view(), name='faq_delete'),
]

backend/faq/urls.py
from django.urls import path
from faq import views

app_name = 'faq'
urlpatterns = [
    path('', views.FAQView.as_view(), name='faq'),
]

backend/tournament/urls.py
from django.urls import path
from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('download/', views.DownloadView.as_view(), name='download'),
]

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="keywords" content="HTML5 Template" />
<meta name="description" content="Sports" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />

<title>{% block title %} {% endblock title %}</title>

<!-- favicon icon -->
<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />

<!-- bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

<!-- animate -->
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}"/>

<!-- owl-carousel -->
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">

<!-- fontawesome -->
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}"/>

<!-- themify -->
<link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}"/>

<!-- flaticon -->
<link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}"/>


<!-- REVOLUTION LAYERS STYLES -->

    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/layers.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/settings.css' %}">

<!-- prettyphoto -->
<link rel="stylesheet" type="text/css" href="{% static 'css/prettyPhoto.css' %}">

<!-- twentytwenty -->
<link rel="stylesheet" type="text/css" href="{% static 'css/twentytwenty.css' %}"/>

<!-- shortcodes -->
<link rel="stylesheet" type="text/css" href="{% static 'css/shortcodes.css' %}"/>

<!-- main -->
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>

<!-- responsive -->
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>

</head>

<body>

    <!--page start-->
    <div class="page">

        <!-- preloader start -->
        <div id="preloader">
           <div id="status">&nbsp;</div>
        </div>
        <!-- preloader end -->

        <!--header start-->
        <header id="masthead" class="header ttm-header-style-classicinfo">
            <div class="ttm-header-wrap">
                <!-- ttm-stickable-header-w -->
                <div id="ttm-stickable-header-w" class="ttm-stickable-header-w ttm-bgcolor-white clearfix ">
                    <div id="site-header-menu" class="site-header-menu">
                        <div class="site-header-menu-inner ttm-stickable-header fixed-header">
                            <div class="container">
                                <!-- site-branding -->
                                <div class="site-branding">
                                    <a class="home-link" href="{% url 'tournament:index' %}" title="Delmont" rel="home">
                                        <img width="151" height="33" id="logo-img" class="img-center" src="{% static 'images/logo-img.png' %}" alt="logo-img">
                                    </a>
                                </div><!-- site-branding end -->
                                <!--site-navigation -->
                                <div id="site-navigation" class="site-navigation">

                                    <div class="ttm-menu-toggle">
                                        <input type="checkbox" id="menu-toggle-form" />
                                        <label for="menu-toggle-form" class="ttm-menu-toggle-block">
                                            <span class="toggle-block toggle-blocks-1"></span>
                                            <span class="toggle-block toggle-blocks-2"></span>
                                            <span class="toggle-block toggle-blocks-3"></span>
                                        </label>
                                    </div>
                                    <nav id="menu" class="menu">
                                        <ul class="dropdown">
                                            <li class="active"><a href="{% url 'tournament:index' %}">Home</a></li>
                                            <li>
                                                <a href="">Tournaments</a>
                                                <ul>
                                                    <li><a href="">Men's T20 International</a></li>
                                                    <li><a href="">Women's T20 International</a></li>
                                                    <li><a href="">BPL</a></li>
                                                    <li><a href="">IPL</a></li>
                                                    <li><a href="">BBL</a></li>
                                                    <li><a href="">WBBL</a></li>
                                                    <li><a href="">T20 Blast</a></li>
                                                    <li><a href="">PSL</a></li>
                                                    <li><a href="">LPL</a></li>
                                                    <li><a href="">CPL</a></li>
                                                    <li><a href="">Men's Super Smash</a></li>
                                                    <li><a href="">Women's Super Smash</a></li>
                                                    <li><a href="">CSA T20</a></li>
						                            <li><a href="">WCSL</a></li>
                                                </ul>
                                            </li>
                                            {% if request.user.is_authenticated %}
                                                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                                                <li><a href="{% url 'account:logout' %}">Sign Out</a></li>
                                            {% else %}
                                                <li><a href="{% url 'account:login' %}">Log In</a></li>
                                            {% endif %}
                                            <li>
                                                <a href="">Others</a>
                                                <ul>
                                                    <li><a href="{% url 'faq:faq' %}">Frequently Asked Questions</a></li>
                                                    <li><a href="">About Us</a></li>
                                                    <li><a href="{% url 'contactus:contactus_form' %}">Contact Us</a></li>
                                                    <li><a href="{% url 'tournament:download' %}">Download</a></li>
                                                </ul>
                                            </li>
                                            {% if request.user.is_superuser %}
                                                <li><a href="{% url 'dashboard:dashboard_index' %}" >Admin Dashboard</a></li>
                                            {% endif %}

                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        {% block body %}
        {% endblock %}


        <!--footer start-->
        <footer class="footer widget-footer clearfix">
            <div class="bottom-footer-text ttm-textcolor-white">
                <div class="container">
                    <div class="row copyright">
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 widget-area">
                            <div class="textwidget widget-text">
                                <div class="social-icons social-hover">
                                    <ul class="list-inline">
                                        <li class="social-facebook"><a class="tooltip-top" target="_blank" href="#" rel="noopener" aria-label="facebook" data-tooltip="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                        <li class="social-twitter"><a class="tooltip-top" target="_blank" href="#" rel="noopener" aria-label="twitter" data-tooltip="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li class="social-gplus"><a class=" tooltip-top" target="_blank" href="#" rel="noopener" aria-label="gplus" data-tooltip="Google+"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                                        <li class="social-linkedin"><a class=" tooltip-top" target="_blank" href="#"
                                        rel="noopener" aria-label="linkedin" data-tooltip="LinkedIn"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <span>Copyright © 2023</span>
                        </div>
                        <div class="col-md-4">
                            <ul id="menu-footer-menu" class="footer-nav-menu">
                                <li><a href="">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--footer end-->

        <!--back-to-top start-->
        <a id="totop" href="#top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!--back-to-top end-->

    </div><!-- page end -->


    <!-- Javascript -->

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.js' %}"></script>
    <script src="{% static 'js/jquery-waypoints.js' %}"></script>
    <script src="{% static 'js/jquery-validate.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/numinate.min.js' %}"></script>
    <script src="{% static 'js/jquery.event.move.js' %}"></script>
    <script src="{% static 'js/jquery.twentytwenty.js' %}"></script>
    <script src="{% static 'js/booked-calendar.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Revolution Slider -->
    <script src="{% static 'revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'revolution/js/slider.js' %}"></script>



    <script src="{% static 'revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
    <script src="{% static 'revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>

    <!-- Javascript end-->

</body>

</html>

backend/templates/change_password.html
{% extends 'base.html' %}
{% block title %} New Password || T-20 Predictor {% endblock title %}

{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <!--site-main start-->
    <div class="site-main" style="height: 100vh;">
        <section class="ttm-row team-section ttm-bg ttm-bgimage-yes ttm-bgcolor-darkgrey h-100 clearfix">
            <div class="container">
               <div class="row">
                    <div class="col-md-7 m-auto">
                        <div class="spacing-4 ttm-bgcolor-white">

                            <div class="container">
                              {% if messages %}
                                  {% for message in messages %}
                                    <div class="alert alert-{{message.tags}}">{{message}}</div>
                                  {% endfor %}
                              {% endif %}
                            </div>

                            <!-- section title -->
                            <div class="section-title with-desc text-center clearfix">
                                <div class="title-header">
                                    <h2 class="title ttm-textcolor-skincolor" style="color: #0D3B4A;">New Password</h2>
                                </div>
                            </div><!-- section title end -->
                            <form id="ttm-make-appoint-form" class="ttm-make-appoint-form wrap-form mt_15 clearfix" method="post" action="">

                                {% csrf_token %}

                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <span class="text-input">
                                                <i class="ttm-textcolor-skincolor ti-timer"></i>
                                                <input name="password1" type="password" value="" placeholder="New Password" required="required">
                                            </span>
                                        </label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <span class="text-input">
                                                <i class="ttm-textcolor-skincolor ti-timer"></i>
                                                <input name="password2" type="password" value="" placeholder="Confirm Password" required="required">
                                            </span>
                                        </label>
                                    </div>
                                </div>

                                <input name="submit" type="submit" id="submit" class="submit" value="Submit">

                            </form>

                        </div>
                    </div>
               </div>
           </div>
        </section>
    </div>
    <!--site-main end-->

{% endblock %}

backend/templates/forgot_password.html
{% extends 'base.html' %}
{% block title %} Reset Password || T-20 Predictor {% endblock title %}

{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <!--site-main start-->
    <div class="site-main" style="height: 100vh;">
        <section class="ttm-row team-section ttm-bg ttm-bgimage-yes ttm-bgcolor-darkgrey h-100 clearfix">
            <div class="container">
               <div class="row">
                    <div class="col-md-7 m-auto">
                        <div class="spacing-4 ttm-bgcolor-white">

                            <div class="container">
                              {% if messages %}
                                  {% for message in messages %}
                                    <div class="alert alert-{{message.tags}}">{{message}}</div>
                                  {% endfor %}
                              {% endif %}
                            </div>

                            <!-- section title -->
                            <div class="section-title with-desc text-center clearfix">
                                <div class="title-header">
                                    <h2 class="title ttm-textcolor-skincolor" style="color: #0D3B4A;">Reset Password</h2>
                                </div>
                            </div><!-- section title end -->
                            <form id="ttm-make-appoint-form" class="ttm-make-appoint-form wrap-form mt_15 clearfix" method="post" action="">

                                {% csrf_token %}

                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <span class="text-input">
                                                <i class="ttm-textcolor-skincolor ti-user"></i>
                                                <input name="email" type="email" value="" placeholder="Email" required="required">
                                            </span>
                                        </label>
                                    </div>
                                </div>

                                <input name="submit" type="submit" id="submit" class="submit" value="Submit Email">
                                <p class="p-4 text-center"><a href="{% url 'account:register' %}">Create an account</a></p>
                            </form>

                        </div>
                    </div>
               </div>
           </div>
        </section>
    </div>
    <!--site-main end-->

{% endblock %}

backend/templates/login.html
{% extends 'base.html' %}
{% block title %} Sign In || T-20 Predictor {% endblock title %}

{% load static %}

{% block body %}

    <!--site-main start-->
    <div class="site-main">
        <section class="ttm-row team-section ttm-bg ttm-bgimage-yes ttm-bgcolor-darkgrey h-100 clearfix">
            <div class="container">
               <div class="row">
                    <div class="col-md-7 m-auto">
                        <div class="spacing-4 ttm-bgcolor-white">

                            <div class="container">
                              {% if messages %}
                                  {% for message in messages %}
                                    <div class="alert alert-{{message.tags}}">{{message}}</div>
                                  {% endfor %}
                              {% endif %}
                            </div>

                            <!-- section title -->
                            <div class="section-title with-desc text-center clearfix">
                                <div class="title-header">
                                    <h2 class="title ttm-textcolor-skincolor" style="color: #0D3B4A;">Login</h2>
                                </div>
                            </div><!-- section title end -->
                            <form id="ttm-make-appoint-form" class="ttm-make-appoint-form wrap-form mt_15 clearfix" method="post" action="">

                                {% csrf_token %}

                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <span class="text-input">
                                                <i class="ttm-textcolor-skincolor ti-user"></i>
                                                <input name="email" type="email" placeholder="Email" required="required">
                                            </span>
                                        </label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <span class="text-input">
                                                <i class="ttm-textcolor-skincolor ti-timer"></i>
                                                <input name="password" type="password" placeholder="Password" required="required">
                                            </span>
                                        </label>
                                    </div>
                                </div>

                                <input name="submit" type="submit" id="submit" class="submit" value="Login">
                                <h6 class="p-3 text-center"><a href="{% url 'account:forgot-password' %}">Forgot Password?</a></h6>
                                <h6 class="text-center"><a href="{% url 'account:register' %}">Create an account</a></h6>
                            </form>

                        </div>
                    </div>
               </div>
           </div>
        </section>
    </div>
    <!--site-main end-->

{% endblock %}

backend/templates/profile.html
{% extends 'base.html' %}
{% block title %} Profile || T-20 Predictor {% endblock title %}

{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <!--site-main start-->
    <div class="site-main" style="height: 100vh;">
        <section class="ttm-row team-section  h-100 clearfix">
            <div class="container">
               <div class="row">
                    <div class="col-lg-12">
                        <div class="ttm-team-member-single-content">
                            <div class="row">
                                <div class="col-lg-5 col-md-12">
                                    <!-- ttm-featured-wrapper -->
                                    <div class="ttm-featured-wrapper">
                                        <div class="featured-thumbnail">
                                            <img class="img-fluid" src="{% static 'images/team-member/team.png' %}" alt="image" height="100%" width="100%">
                                        </div>
                                    </div><!-- ttm-featured-wrapper end-->
                                </div>
                                <div class="ttm-team-member-single-content-area col-md-12 col-lg-7">
                                    <div class="ttm-team-member-content shadow-box">
                                        <div class="ttm-team-member-single-list">
                                            <h2 class="ttm-team-member-single-title">{{ profile.first_name }} {{ profile.last_name }}</h2>
                                            <h5 class="ttm-team-member-single-position"><b>{{ profile.user_type }}</b></h5>
                                            <div class="ttm-team-member-appointment-btn-wrapper">
                                                <a class="ttm-btn ttm-btn-size-md ttm-btn-shape-square ttm-btn-style-fill ttm-btn-color-skincolor mb-20" href="{% url 'account:profile-form' %}">EDIT PROFILE</a>
                                            </div>
                                            <div class="ttm-team-data">
                                                <div class="ttm-team-details-wrapper">
                                                    <ul class="ttm-team-details-list clearfix">
                                                        <li>
                                                            <div class="ttm-team-list-title">
                                                                <i class="fa fa-phone"></i> Phone :
                                                            </div>
                                                            <div class="ttm-team-list-value"><a href="tel:{{ profile.phone }}"> {{ profile.phone }} </a></div>
                                                        </li>
                                                        <li>
                                                            <div class="ttm-team-list-title">
                                                                <i class="ti ti-email"></i> Email :
                                                            </div>
                                                            <div class="ttm-team-list-value">
                                                                <a href="mailto:info@example.com" tabindex="0"> {{ profile.email_id }} </a>
                                                            </div>
                                                        </li>
                                                         <li>
                                                            <div class="ttm-team-list-title">
                                                                <i class="ti ti-location-pin"></i> Address Info :
                                                            </div>
                                                             <div class="ttm-team-list-value"> <p> {{ profile.address }}, {{ profile.city }}, {{ profile.country }} - {{ profile.zipcode }} </p> </div>
                                                        </li>
                                                        <li>
                                                            <div class="ttm-team-list-title">
                                                                <i class="ti ti-location-pin"></i> Bio :
                                                            </div>
                                                            <div class="ttm-team-list-value"> <p> {{ profile.bio }} </p> </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
           </div>
        </section>
    </div><!--site-main end-->

{% endblock %}

backend/templates/register.html
{% extends 'base.html' %}
{% block title %} Sign Up || T-20 Predictor {% endblock title %}

{% load static %}
{% load crispy_forms_tags %}

{% block body %}


    <!--site-main start-->
    <div class="site-main">
        <section class="ttm-row team-section ttm-bg ttm-bgimage-yes ttm-bgcolor-darkgrey h-100 clearfix">
            <div class="container">
               <div class="row">
                    <div class="col-md-7 m-auto">
                        <div class="spacing-4 ttm-bgcolor-white">
                            <!-- section title -->
                            <div class="section-title with-desc text-center clearfix">
                                <div class="title-header">
                                    <h2 class="title ttm-textcolor-skincolor" style="color: #0D3B4A;">Sign Up</h2>
                                </div>
                            </div><!-- section title end -->
                            <form id="ttm-make-appoint-form" class="ttm-make-appoint-form wrap-form mt_15 clearfix" method="post" action="#">

                                {% csrf_token %}

                                {{form | crispy}}

                                <input name="submit" type="submit" id="submit" class="submit" value="Sign Up Now">
                                <h6 class="p-4 text-center"><a href="{% url 'account:login' %}">Already have an account? Login</a></h6>
                            </form>

                        </div>
                    </div>
               </div>
           </div>
        </section>
    </div>
<!--site-main end-->


{% endblock %}